# Generated by Django 3.2.20 on 2023-12-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('desc', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='tovar/', verbose_name='Фото товара')),
                ('price', models.IntegerField(verbose_name='Цена: ')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
