# Generated by Django 3.2.20 on 2023-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
